services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kaspa-backend
    env_file:
      - ./backend/.env
    environment:
      - USE_QDRANT=true
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - BACKEND_URL=http://0.0.0.0:8001
    depends_on:
      - qdrant
    ports:
      - "8001:8001"
    volumes:
      - ./backend/db:/app/backend/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kaspa-frontend
    env_file:
      - ./frontend/.env
    environment:
      - PORT=5173
    depends_on:
      - backend
    ports:
      - "5173:5173"

